project:
  type: website
  output-dir: docs

website:
  title: "Aspen Jack"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: projects.qmd
        text: Projects

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    embed-resources: true



