project:
  type: website
  output-dir: docs

website:
  title: "Aspen Jack"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Portfolio
      - href: resume.qmd
        text: Resume
      - about.qmd
      - href: contact.qmd
        text: Contact

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    embed-resources: true



