project:
  type: website
  output-dir: docs

website:
  title: "Aspen Jack"
  navbar:
    background: "#D2B4DE"
    foreground: light
    left:
      - href: index.qmd
        text: Home
      - href: portfolio.qmd
        text: Portfolio
      - href: resume.qmd
        text: Resume
      - about.qmd
      - href: contact.qmd
        text: Contact

    

format:
  html:
    theme: journal
    linkcolor: "#512E5F"
    css: styles.css
    toc: true
    embed-resources: true
    page-layout: full



